-- Phase 2 Schema: Properties, Units, Tenants, Contracts

-- 1. PROPERTIES (Nemovitosti/Byty)
create table public.properties (
  id bigint generated by default as identity primary key,
  name text not null, -- e.g. "Byt Praha 2"
  address jsonb not null, -- { street, city, zip, specificLocation }
  landlord_info jsonb not null, -- { name, birthNumber, address, contact, bankAccount }
  settings jsonb not null, -- { rentDueDay, noticePeriodMonths, defaultDuration, servicesBreakdown, securityDeposit }
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  owner_id uuid references auth.users not null -- Admin/Owner who manages this property
);

-- RLS for Properties
alter table public.properties enable row level security;
create policy "Admins can manage properties" on public.properties
  using (public.is_admin());

-- 2. RENTAL UNITS (Varianty pokojů)
create table public.rental_units (
  id bigint generated by default as identity primary key,
  property_id bigint references public.properties(id) on delete cascade not null,
  name text not null, -- e.g. "Malý pokoj"
  description text,
  monthly_rent integer not null,
  fee_per_person integer not null,
  max_occupants integer not null default 1,
  area_m2 numeric,
  features text[], -- Array of strings e.g. ['postel', 'stůl']
  meter_readings jsonb, -- Default logic/config for meters
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Units
alter table public.rental_units enable row level security;
create policy "Admins can manage units" on public.rental_units
  using (public.is_admin());
create policy "Public/Generators can read units" on public.rental_units
  for select using (true); -- Publicly viewable for generator usage? Or restricted to auth users?

-- 3. TENANTS (Nájemníci / Osoby)
create table public.tenants (
  id uuid default gen_random_uuid() primary key,
  first_name text not null,
  last_name text not null,
  email text,
  phone text,
  birth_number text, -- Rodné číslo
  address_permanent text,
  user_id uuid references auth.users, -- Link to system user if they register later
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Tenants
alter table public.tenants enable row level security;
create policy "Admins can manage tenants" on public.tenants
  using (public.is_admin());
create policy "Users can read own tenant record" on public.tenants
  using (auth.uid() = user_id);
-- Generator needs to insert new tenants:
create policy "Authenticated users can insert tenants" on public.tenants
  for insert with check (auth.role() = 'authenticated'); 

-- 4. CONTRACTS (Smlouvy)
create table public.contracts (
  id uuid default gen_random_uuid() primary key,
  unit_id bigint references public.rental_units(id),
  tenant_id uuid references public.tenants(id),
  status text not null default 'draft', -- draft, active, terminated
  
  date_from date not null,
  date_to date,
  date_signed date,
  
  -- Financial Snapshot (locking prices at time of creation)
  rent_price integer not null,
  fees_price integer not null,
  deposit_amount integer,
  
  -- Metadata
  created_by uuid references auth.users,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Contracts
alter table public.contracts enable row level security;
create policy "Admins can manage all contracts" on public.contracts
  using (public.is_admin());
create policy "Tenants can read own agreements" on public.contracts
  for select using (
    exists (
      select 1 from public.tenants 
      where public.tenants.id = public.contracts.tenant_id 
      and public.tenants.user_id = auth.uid()
    )
  );
create policy "Generator users can insert contracts" on public.contracts
  for insert with check (auth.role() = 'authenticated');
