-- v3_schema_update.sql
-- Goal: Add support for Households, Shared Areas, Equipment, and Role-based Sharing.

-- 1. ENHANCE PROPERTIES
-- Add columns for shared area dimensions and common equipment
alter table public.properties 
add column if not exists shared_area_m2 numeric,
add column if not exists equipment text[]; -- e.g. ["pračka", "lednička"] in shared areas

-- 2. CREATE PROPERTY_ROLES (Sharing)
-- Allows multiple users to have access to a property with specific roles
create table if not exists public.property_roles (
  id bigint generated by default as identity primary key,
  property_id bigint references public.properties(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  role text not null check (role in ('landlord', 'manager', 'tenant')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(property_id, user_id)
);

-- 3. ENABLE RLS FOR PROPERTY_ROLES
alter table public.property_roles enable row level security;

-- Policy: Owners (from properties table) can manage roles for their properties
create policy "Owners can manage property roles" on public.property_roles
  using (
    exists (
      select 1 from public.properties
      where public.properties.id = public.property_roles.property_id
      and public.properties.owner_id = auth.uid()
    )
  );

-- Policy: Users can read their own roles (to see what they have access to)
create policy "Users can read own roles" on public.property_roles
  for select
  using (auth.uid() = user_id);

-- 4. UPDATE/ADD HELPER FUNCTIONS FOR ACCESS CONTROL

-- Function to check if a user has access to a property (Owner OR has a role)
create or replace function public.has_property_access(req_property_id bigint)
returns boolean
language sql
security definer
stable
as $$
  select exists (
    select 1 from public.properties 
    where id = req_property_id 
    and owner_id = auth.uid()
    
    union all
    
    select 1 from public.property_roles 
    where property_id = req_property_id 
    and user_id = auth.uid()
  );
$$;

-- 5. UPDATE POLICIES ON PROPERTIES (Optional - if we want to allow Managers to edit)
-- Currently only "Admins" (global) and owners can manage using existing policies.
-- We should update this to allow Property Managers to edit specific properties.

-- Drop old policy if it conflicts or just add a new one? 
-- Existing policy in v2: "Admins can manage properties" using (public.is_admin());
-- We likely need a policy for "Owners and Managers can update their properties"

create policy "Owners and Managers can update properties" on public.properties
  for update
  using (
    owner_id = auth.uid() 
    or 
    exists (
      select 1 from public.property_roles
      where property_id = public.properties.id
      and user_id = auth.uid()
      and role in ('landlord', 'manager')
    )
  );

create policy "Owners and Managers can view properties" on public.properties
  for select
  using (
    owner_id = auth.uid() 
    or 
    exists (
      select 1 from public.property_roles
      where property_id = public.properties.id
      and user_id = auth.uid()
    )
  );
