-- 1. Table for multiple people on one contract (Tenants + Subtenants)
create table public.contract_members (
  id bigint generated by default as identity primary key,
  contract_id uuid references public.contracts(id) on delete cascade not null,
  tenant_id uuid references public.tenants(id) on delete cascade not null,
  role text not null check (role in ('main_tenant', 'subtenant', 'occupant')), 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Prevent duplicate linking of same person to same contract
  unique(contract_id, tenant_id)
);

-- RLS for Contract Members
alter table public.contract_members enable row level security;

create policy "Admins can manage contract members" on public.contract_members
  using (public.is_admin());

create policy "Members can view their own membership" on public.contract_members
  for select using (
    exists (
      select 1 from public.tenants 
      where public.tenants.id = public.contract_members.tenant_id 
      and public.tenants.user_id = auth.uid()
    )
  );

-- 2. View for "Persons in Flat" (Who is where and when)
-- This view joins Properties -> Units -> Contracts -> Members -> Tenants
create or replace view public.view_unit_occupancy as
select 
  p.id as property_id,
  p.name as property_name,
  u.id as unit_id,
  u.name as unit_name,
  t.id as tenant_id,
  t.first_name,
  t.last_name,
  t.email,
  t.phone,
  cm.role,
  c.id as contract_id,
  c.status as contract_status,
  c.date_from,
  c.date_to,
  -- Check if currently active based on dates and status
  (c.status = 'active' and 
   current_date >= c.date_from and 
   (c.date_to is null or current_date <= c.date_to)) as is_currently_active
from public.contracts c
join public.rental_units u on c.unit_id = u.id
join public.properties p on u.property_id = p.id
join public.contract_members cm on c.id = cm.contract_id
join public.tenants t on cm.tenant_id = t.id;

-- Grant access to view
grant select on public.view_unit_occupancy to authenticated;
grant select on public.view_unit_occupancy to service_role;
